name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    #БД для тестирования в GitHubActions
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_is_ready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build with Gradle
        run: ./gradlew compileJava

      - name: Run tests
        env:
          JDBC_URL: jdbc:postgresql://postgres:5432/test_db
          JDBC_USER: user
          JDBC_PASSWORD: password
        run: ./gradlew test